version: '3.8'

services:
  web:
    build: .
    # container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: password
      MYSQL_DB: flask_db

  mysql:
    image: mysql:5.7
    # container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: password
    # ports:
    #   - "3307:3306"